name: Setup Project Files (Idempotent Multi-File)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with write token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for required files
        id: check_files
        run: |
          MISSING=()

          if [ ! -f status.txt ]; then
            echo "status.txt is missing"
            MISSING+=("status.txt")
          fi

          if [ ! -f .env.example ]; then
            echo ".env.example is missing"
            MISSING+=(".env.example")
          fi

          if [ ! -f config.json ]; then
            echo "config.json is missing"
            MISSING+=("config.json")
          fi

          echo "missing_files=${MISSING[*]}" >> $GITHUB_OUTPUT
          echo "file_count=${#MISSING[@]}" >> $GITHUB_OUTPUT

      - name: Create missing files (if any)
        if: steps.check_files.outputs.file_count != '0'
        run: |
          for FILE in ${{ steps.check_files.outputs.missing_files }}; do
            case "$FILE" in
              "status.txt")
                echo "This file indicates the initial setup is complete." > status.txt
                ;;
              ".env.example")
                echo "DB_HOST=localhost" > .env.example
                echo "DB_PORT=3306" >> .env.example
                ;;
              "config.json")
                echo '{ "debug": true, "version": "1.0.0" }' > config.json
                ;;
            esac
          done

      - name: Commit and push changes
        if: steps.check_files.outputs.file_count != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add status.txt .env.example config.json || true
          git commit -m "feat: Add missing setup files [auto-generated]" || echo "Nothing to commit"
          git push
