# .github/workflows/check-and-create-file.yml
name: Demonstrate Idempotence (File Creation)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ensure-file-exists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code with write token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if 'status.txt' already exists
        id: check_file
        run: |
          if [ -f status.txt ]; then
            echo "status.txt already exists. Skipping creation."
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "status.txt does NOT exist. Proceeding to create."
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create and commit status.txt
        if: steps.check_file.outputs.exists == 'false'
        run: |
          echo "This file indicates the initial setup is complete." > status.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add status.txt
          git commit -m "feat: Add status.txt as part of idempotent setup"
          git push
